#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

# On first boot, set the (default) ubuntu user's password to "ubuntu" and
# expire user passwords
chpasswd:
  expire: false
  list:
  - ubuntu:PiK8kE

# Enable password authentication with the SSH daemon
ssh_pwauth: false

# You may add ssh authorized public key(s) to allow remote login via ssh.
# Add each entry to ~/.ssh/authorized_keys for the configured user or the
# first user defined in the user definition directive.
# Please don't delete the existing ssh authorized_key - that is required for
# remote installation and management of Kubernetes via ansible
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDziq78g1bF2L1PABxqHwzM+2xAVfP+ZDzw8DYhNeOQ0OvmVU9cV9vvcWfCvzcuGOXp6XxfWAOOpWfKQjAsgpXgpon+rAL/t/ELx7M71ihsHWr7uIFKI7ZWi/O7lAs0eqo3D3Qkch6oKX1uvZwQJFJJ6DwEaDlzi4asrHCpFjhcb/JGSqe1INdkGRrphVOUuDFeaWxUbCkv6dqgDhU2+tASIa11bzJX336gtakHBbxN7W12mMtAoz4y8cQ5YYdmni7D4h0a9YVF/KqbgYw7hLPAfd2HWowSY2FxjHBX/Xv1kEcQbmSfnX/1iEm8/mXpuV1jGtuuJ/yAZt4bNhofZZfRqpxws/DJfKDiUgk//3h3MoTSChsOpzxAlG0+U6QuA2azAC2yVMCBCePV3KbwSM04oHfWtMlwzFxLr30zxJD/PVESgCFzW2jbbJgxJ9W0tXDHs2MWUY5L9C6YN45F6WABYBa2Q5iCRga92AqxGeXC25hRdFIL5SpuwAz+2LFOK2s= PiK8kE

## On first boot, use ssh-import-id to give the specific users SSH access to
## the default user
#ssh_import_id:
#- lp:my_launchpad_username
#- gh:my_github_username

## Add users and groups to the system, and import keys with the ssh-import-id
## utility
#groups:
#- robot: [robot]
#- robotics: [robot]
#- pi
#
#users:
#- default
#- name: robot
#  gecos: Mr. Robot
#  primary_group: robot
#  groups: users
#  ssh_import_id: foobar
#  lock_passwd: false
#  passwd: $5$hkui88$nvZgIle31cNpryjRfO9uArF7DYiBcWEnjqq7L1AQNN3

## Update apt database and upgrade packages on first boot
#package_update: true
#package_upgrade: true

## Install additional packages on first boot
packages:
- evio
#- pastebinit
#- [libpython2.7, 2.7.3-0ubuntu3.1]

apt:
  sources:
     fury.list:
       source: "deb [trusted=yes] https://apt.fury.io/evio/ * *"

## Write arbitrary files to the file-system (including binaries!)
#write_files:
#- path: /etc/default/keyboard
#  content: |
#    # KEYBOARD configuration file
#    # Consult the keyboard(5) manual page.
#    XKBMODEL="pc105"
#    XKBLAYOUT="gb"
#    XKBVARIANT=""
#    XKBOPTIONS="ctrl: nocaps"
#  permissions: '0644'
#  owner: root:root
#- encoding: gzip
#  path: /usr/bin/hello
#  content: !!binary |
#    H4sIAIDb/U8C/1NW1E/KzNMvzuBKTc7IV8hIzcnJVyjPL8pJ4QIA6N+MVxsAAAA=
#  owner: root:root
#  permissions: '0755'

## Run arbitrary commands at rc.local like time
runcmd:
#- [ cp, /boot/evio-config.json, /etc/opt/evio/config.json ]
- [ systemctl, start, evio ]
#- [ wget, "http://ubuntu.com", -O, /run/mydir/index.html ]
